name: Create s3 Bucket
on: 
  workflow_dispatch:
    inputs:
      bucketname:
        description: 'Enter s3 bucket name'
        required: true
jobs:
  create-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS crendentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Create s3 bucket
        run: aws s3 mb s3://${{ github.event.inputs.bucketname }}
